#pragma once

#undef TEXT

#undef ReadFile
#undef WriteFile

#undef HEAP_NO_SERIALIZE
#undef HEAP_GROWABLE
#undef HEAP_GENERATE_EXCEPTIONS
#undef HEAP_ZERO_MEMORY
#undef HEAP_REALLOC_IN_PLACE_ONLY
#undef HEAP_TAIL_CHECKING_ENABLED
#undef HEAP_FREE_CHECKING_ENABLED
#undef HEAP_DISABLE_COALESCE_ON_FREE
#undef HEAP_CREATE_ALIGN_16
#undef HEAP_CREATE_ENABLE_TRACING
#undef HEAP_CREATE_ENABLE_EXECUTE
#undef HEAP_MAXIMUM_TAG
#undef HEAP_PSEUDO_TAG_FLAG
#undef HEAP_TAG_SHIFT
#undef HEAP_CREATE_SEGMENT_HEAP
#undef HEAP_CREATE_HARDENED

#include "Definitions.h"